import { Patient } from "../shared/types";

export const patients: Patient[] = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        dateOfBirth: "1980-05-15",
        gender: "Male",
        lastVisitDate: "2024-02-15",
        patientDiagnosisDescription: "Hypertension, Type 2 Diabetes",
    },
    {
        id: 2,
        firstName: "Alice",
        lastName: "Smith",
        dateOfBirth: "1992-11-23",
        gender: "Female",
        lastVisitDate: "2024-03-10",
        patientDiagnosisDescription: "Asthma, Seasonal allergies",
    },
    {
        id: 3,
        firstName: "James",
        lastName: "Wilson",
        dateOfBirth: "1965-08-30",
        gender: "Male",
        lastVisitDate: "2024-01-20",
        patientDiagnosisDescription: "Coronary artery disease, Hyperlipidemia",
    },
    {
        id: 4,
        firstName: "Emily",
        lastName: "Johnson",
        dateOfBirth: "1988-04-12",
        gender: "Female",
        lastVisitDate: "2024-02-28",
        patientDiagnosisDescription: "Migraine, Anxiety disorder",
    },
    {
        id: 5,
        firstName: "Michael",
        lastName: "Brown",
        dateOfBirth: "1975-09-18",
        gender: "Male",
        lastVisitDate: "2024-03-05",
        patientDiagnosisDescription:
            "Gastroesophageal reflux disease, Irritable bowel syndrome",
    },
    {
        id: 6,
        firstName: "Sarah",
        lastName: "Davis",
        dateOfBirth: "1990-07-03",
        gender: "Female",
        lastVisitDate: "2024-01-15",
        patientDiagnosisDescription: "Hypothyroidism, Iron deficiency anemia",
    },
    {
        id: 7,
        firstName: "Robert",
        lastName: "Garcia",
        dateOfBirth: "1958-12-10",
        gender: "Male",
        lastVisitDate: "2024-02-10",
        patientDiagnosisDescription: "Osteoarthritis, Gout",
    },
    {
        id: 8,
        firstName: "Jennifer",
        lastName: "Martinez",
        dateOfBirth: "1983-06-25",
        gender: "Female",
        lastVisitDate: "2024-03-18",
        patientDiagnosisDescription: "Polycystic ovary syndrome, Depression",
    },
    {
        id: 9,
        firstName: "David",
        lastName: "Taylor",
        dateOfBirth: "1972-02-14",
        gender: "Male",
        lastVisitDate: "2024-01-30",
        patientDiagnosisDescription: "Sleep apnea, Obesity",
    },
    {
        id: 10,
        firstName: "Lisa",
        lastName: "Anderson",
        dateOfBirth: "1995-10-05",
        gender: "Female",
        lastVisitDate: "2024-02-22",
        patientDiagnosisDescription: "Fibromyalgia, Chronic fatigue syndrome",
    },
    {
        id: 11,
        firstName: "Thomas",
        lastName: "Robinson",
        dateOfBirth: "1968-03-27",
        gender: "Male",
        lastVisitDate: "2024-03-12",
        patientDiagnosisDescription:
            "Benign prostatic hyperplasia, Erectile dysfunction",
    },
    {
        id: 12,
        firstName: "Olivia",
        lastName: "Lee",
        dateOfBirth: "1991-01-09",
        gender: "Female",
        lastVisitDate: "2024-01-25",
        patientDiagnosisDescription: "Endometriosis, Migraines",
    },
    {
        id: 13,
        firstName: "William",
        lastName: "Walker",
        dateOfBirth: "1963-11-17",
        gender: "Male",
        lastVisitDate: "2024-02-18",
        patientDiagnosisDescription:
            "Chronic obstructive pulmonary disease, Emphysema",
    },
    {
        id: 14,
        firstName: "Sophia",
        lastName: "Clark",
        dateOfBirth: "1987-08-22",
        gender: "Female",
        lastVisitDate: "2024-03-07",
        patientDiagnosisDescription: "Multiple sclerosis, Neuropathic pain",
    },
    {
        id: 15,
        firstName: "George",
        lastName: "Hall",
        dateOfBirth: "1979-05-01",
        gender: "Male",
        lastVisitDate: "2024-01-18",
        patientDiagnosisDescription: "Atrial fibrillation, Heart failure",
    },
    {
        id: 16,
        firstName: "Emma",
        lastName: "Young",
        dateOfBirth: "1993-12-28",
        gender: "Female",
        lastVisitDate: "2024-02-25",
        patientDiagnosisDescription: "Celiac disease, Lactose intolerance",
    },
    {
        id: 17,
        firstName: "Richard",
        lastName: "King",
        dateOfBirth: "1960-07-14",
        gender: "Male",
        lastVisitDate: "2024-03-15",
        patientDiagnosisDescription: "Parkinson's disease, Essential tremor",
    },
];
